import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  mainSidebar: [
    {
      id: 'get-started',
      type: 'doc',
      label: 'Get Started',
    },
    {
      type: 'category',
      label: 'Try Each Agent',
      collapsed: false,
      items: [
        'agents/base-agent',
        'agents/ibm-cloud-guide-agent',
        'agents/ibm-cloud-serverless-computing-agent',
        'agents/ibm-cloud-account-admin-agent',
        'agents/ibm-cloud-automation-agent',
      ]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
