name: Deploy React-Based Docs Site.

on:
  push:
    branches:
      - main # on push to main trigger.
  workflow_dispatch: # on actions trigger.

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo.
        uses: actions/checkout@v4

      - name: Setup Node.
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install npm dependencies.
        run: npm ci --ignore-scripts

      - name: Build Docs.
        run: npm run build

      - name: Upload production-ready build files.
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy Docs.
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download next build ready artifacts.
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages.
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
